/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import OBJ.HoaDon;
import OBJ.KhachHang;
import OBJ.SanPham;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.mail.DefaultAuthenticator;
import org.apache.commons.mail.Email;
import org.apache.commons.mail.EmailException;
import org.apache.commons.mail.SimpleEmail;

/**
 *
 * @author truongnguyen
 */
public class frmBanHang extends javax.swing.JPanel {

    /**
     * Creates new form frmBanHang1
     */
    private DefaultTableModel defaultTableModel;
    ArrayList<HoaDon> listGioHang = new ArrayList<>();
    NumberFormat formatter = new DecimalFormat("###,###");
    KhachHang kh = new KhachHang();
    SanPham sp = new SanPham();
    int index;

    public frmBanHang() {
        initComponents();
        //setSize(1059, 680);
        getDataKH(loadKH());
        getDataSP(loadSP());
        lbl_maNhanVien.setText(frmLogin.nameLogin);
        btn_thanhToan.setEnabled(false);
    }

    public ArrayList<KhachHang> loadKH() {
        frmKhachHang frm_KH = new frmKhachHang();
        frm_KH.loadFile();
        return frm_KH.listKH;
    }

    public ArrayList<SanPham> loadSP() {
        frmSanPham frm_SP = new frmSanPham();
        frm_SP.loadFile();
        return frm_SP.listSP;
    }

    private void getDataSP(ArrayList<SanPham> listSP) {
        defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Mã SP");
        defaultTableModel.addColumn("Tên SP");
        defaultTableModel.addColumn("Đơn vị tính");
        defaultTableModel.addColumn("Tên NSX");
        defaultTableModel.addColumn("Số lượng");
        defaultTableModel.addColumn("Giá bán");

        for (SanPham obj : listSP) {
            Vector vector = new Vector();
            vector.add(obj.getMaSP());
            vector.add(obj.getTen());
            vector.add(obj.getDonViTinh());
            vector.add(obj.getTenNSX());
            vector.add(formatter.format(obj.getSoLuong()));
            vector.add(formatter.format(Integer.parseInt(obj.getGiaBan())));
            defaultTableModel.addRow(vector);
        }
        tbl_san_pham.setModel(defaultTableModel);
    }

    private void getDataKH(ArrayList<KhachHang> listKH) {
        defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Mã KH");
        defaultTableModel.addColumn("Họ tên KH");
        defaultTableModel.addColumn("Email");
        defaultTableModel.addColumn("SĐT");
        for (KhachHang obj : listKH) {
            if (obj.getTrangThai() == 1) {
                Vector vector = new Vector();
                vector.add(obj.getMaKhachHang());
                vector.add(obj.getHoTen());
                vector.add(obj.getEmail());
                vector.add(obj.getSoDienThoai());
                defaultTableModel.addRow(vector);
            }

        }
        tbl_khach_hang.setModel(defaultTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btl_thanhToan = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txt_searchKH = new javax.swing.JTextField();
        btl_khachHang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_khach_hang = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        txt_sanPham = new javax.swing.JTextField();
        btl_sanPham = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_san_pham = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txt_soLuongSP = new javax.swing.JTextField();
        btl_themSP = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_sdtKH = new javax.swing.JLabel();
        lbl_maKH = new javax.swing.JLabel();
        lbl_tenKH = new javax.swing.JLabel();
        lbl_emailKH = new javax.swing.JLabel();
        lbl_diaChiKH = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_gioHang = new javax.swing.JTable();
        btl_xoaGioHang = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lbl_tongTien = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_thanhToan = new javax.swing.JButton();
        btl_thoat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_maNhanVien = new javax.swing.JLabel();

        btl_thanhToan.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        btl_thanhToan.setText("Thanh Toán");
        btl_thanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btl_thanhToanActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(1059, 680));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Khách Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 0, 0))); // NOI18N

        btl_khachHang.setText("Tìm Kiếm");
        btl_khachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btl_khachHangActionPerformed(evt);
            }
        });

        tbl_khach_hang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_khach_hang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_khach_hangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_khach_hang);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(txt_searchKH, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btl_khachHang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_searchKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btl_khachHang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 0, 51))); // NOI18N

        txt_sanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sanPhamActionPerformed(evt);
            }
        });

        btl_sanPham.setText("Tìm Kiếm");

        tbl_san_pham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_san_pham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_san_phamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_san_pham);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel11.setText("Số Lượng: ");

        txt_soLuongSP.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txt_soLuongSP.setText("0");
        txt_soLuongSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soLuongSPActionPerformed(evt);
            }
        });

        btl_themSP.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btl_themSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shop-cart-add-icon.png"))); // NOI18N
        btl_themSP.setText("Thêm vào giỏ hàng");
        btl_themSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btl_themSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(txt_sanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btl_sanPham)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_soLuongSP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btl_themSP)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btl_sanPham))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_soLuongSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btl_themSP))
                .addGap(65, 65, 65))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel7.setForeground(new java.awt.Color(0, 0, 255));

        jLabel2.setText("Mã KH: ");

        jLabel3.setText("Họ Và Tên: ");

        jLabel5.setText("Số điện thoại: ");

        jLabel6.setText("Địa chỉ: ");

        jLabel7.setText("Email: ");

        lbl_sdtKH.setForeground(new java.awt.Color(0, 0, 255));
        lbl_sdtKH.setText("....");

        lbl_maKH.setForeground(new java.awt.Color(0, 51, 255));
        lbl_maKH.setText("....");

        lbl_tenKH.setForeground(new java.awt.Color(0, 0, 255));
        lbl_tenKH.setText("............................");

        lbl_emailKH.setForeground(new java.awt.Color(0, 0, 255));
        lbl_emailKH.setText("..........................");

        lbl_diaChiKH.setForeground(new java.awt.Color(0, 0, 255));
        lbl_diaChiKH.setText(".......................");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel8.setText("Giỏ hàng: ");

        tbl_gioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_gioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_gioHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl_gioHangMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_gioHang);

        btl_xoaGioHang.setText("Xóa khỏi giỏ hàng");
        btl_xoaGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btl_xoaGioHangActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel9.setText("Tổng tiền: ");

        lbl_tongTien.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lbl_tongTien.setForeground(new java.awt.Color(0, 51, 204));
        lbl_tongTien.setText("........");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel10.setText("(VND)");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_diaChiKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_maKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_sdtKH, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_emailKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_tenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(lbl_tongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel10))
                                .addComponent(btl_xoaGioHang, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lbl_maKH)
                    .addComponent(lbl_tenKH))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(lbl_sdtKH)
                    .addComponent(lbl_emailKH))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbl_diaChiKH))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btl_xoaGioHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbl_tongTien)
                    .addComponent(jLabel10))
                .addGap(62, 62, 62))
        );

        btn_thanhToan.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btn_thanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/coin-us-dollar-icon.png"))); // NOI18N
        btn_thanhToan.setText("Thanh Toán");
        btn_thanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thanhToanActionPerformed(evt);
            }
        });

        btl_thoat.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btl_thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Users-Exit-icon.png"))); // NOI18N
        btl_thoat.setText("Thoát");

        jPanel1.setBackground(new java.awt.Color(255, 115, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/danhmuc.png"))); // NOI18N
        jLabel1.setText("HÓA ĐƠN BÁN HÀNG");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Zent Coding School");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nhân Viên: ");

        lbl_maNhanVien.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbl_maNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        lbl_maNhanVien.setText("NV01");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel4)
                .addGap(174, 174, 174)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_maNhanVien)
                .addGap(91, 91, 91))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1)
                .addComponent(jLabel12)
                .addComponent(lbl_maNhanVien))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_thanhToan)
                        .addGap(79, 79, 79)
                        .addComponent(btl_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_thanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btl_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_soLuongSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soLuongSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soLuongSPActionPerformed
    double tongTien = 0;
    private void btl_themSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btl_themSPActionPerformed
        int soLuongMua = Integer.parseInt(txt_soLuongSP.getText());
        if (soLuongMua <= 0) {
            JOptionPane.showMessageDialog(this, "Số lượng sản phẩm phải > 0!");
        } else if (soLuongMua > sp.getSoLuong()) {
            JOptionPane.showMessageDialog(this, "Số lượng sản phẩm lớn hơn số lượng trong kho!");
        } else {
            //Thỏa mãn
            HoaDon hd = new HoaDon();
            hd.setMaSP(sp.getMaSP());
            hd.setSoLuong(soLuongMua);
            hd.setDonGia(Double.parseDouble(sp.getGiaBan()));
            hd.setThanhTien(soLuongMua * Double.parseDouble(sp.getGiaBan()));
            if (checkSPExistGioHang(hd.getMaSP(), listGioHang)) {
                HoaDon hoaDon = listGioHang.get(indexMaSPTrungTrongGioHang);
                hoaDon.setSoLuong(Integer.parseInt(txt_soLuongSP.getText()) + hoaDon.getSoLuong());
                listGioHang.set(indexMaSPTrungTrongGioHang, hoaDon);

            } else {
                listGioHang.add(hd);
            }
            loadGioHang(listGioHang);
            JOptionPane.showMessageDialog(this, "Thêm giỏ hàng thành công !");
            tongTien = 0;
            for (int i = 0; i < listGioHang.size(); i++) {
                tongTien += listGioHang.get(i).getThanhTien();
            }
            lbl_tongTien.setText(formatter.format(tongTien));
        }
    }//GEN-LAST:event_btl_themSPActionPerformed
    int indexMaSPTrungTrongGioHang;

    public boolean checkSPExistGioHang(String maSP, ArrayList<HoaDon> listHD) {
        for (int i = 0; i < listHD.size(); i++) {
            if (maSP.equals(listHD.get(i).getMaSP())) {
                indexMaSPTrungTrongGioHang = i;
                return true;
            }
        }
        return false;
    }

    public void loadGioHang(ArrayList<HoaDon> listHD) {
        defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Mã SP");
        defaultTableModel.addColumn("Tên sản phẩm");
        defaultTableModel.addColumn("ĐVT");
        defaultTableModel.addColumn("SL mua");
        defaultTableModel.addColumn("Đơn giá");
        defaultTableModel.addColumn("Thành tiền");
        for (HoaDon obj : listHD) {
            SanPham sp = new frmBanHang().getSPByCode(obj.getMaSP());
            Vector vector = new Vector();
            vector.add(obj.getMaSP());
            vector.add(sp.getTen());
            vector.add(sp.getDonViTinh());
            vector.add(formatter.format(obj.getSoLuong()));
            vector.add(formatter.format(obj.getDonGia()));
            vector.add(formatter.format(obj.getThanhTien()));
            defaultTableModel.addRow(vector);

        }
        tbl_gioHang.setModel(defaultTableModel);
        if (listHD.size() > 0) {
            btn_thanhToan.setEnabled(true);
        } else {
            btn_thanhToan.setEnabled(false);
        }
    }

    public SanPham getSPByCode(String maSP) {
        ArrayList<SanPham> listSP = loadSP();
        for (int i = 0; i < listSP.size(); i++) {
            if (maSP.equals(listSP.get(i).getMaSP())) {
                return listSP.get(i);
            }
        }
        return null;
    }
    private void btl_xoaGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btl_xoaGioHangActionPerformed
        double tienGiam;
        for (int i = 0; i < listGioHang.size(); i++) {
            if (maSP.equals(listGioHang.get(i).getMaSP())) {
                tienGiam = listGioHang.get(i).getThanhTien();
                listGioHang.remove(i);
                tongTien = tongTien - tienGiam;
                lbl_tongTien.setText(String.valueOf(tongTien));
            }
        }
        loadGioHang(listGioHang);
    }//GEN-LAST:event_btl_xoaGioHangActionPerformed

    private void btl_thanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btl_thanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btl_thanhToanActionPerformed

    private void btn_thanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thanhToanActionPerformed
        if (kh.getMaKhachHang() == null || kh.getMaKhachHang().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khách hàng trước !");
            return;
        } else {
            Date date = new Date();
            //Định dạng hóa đơn: KH01_03082019105220
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy-hh-mm-ss");
            SimpleDateFormat sdf2 = new SimpleDateFormat("dd-MM-yyyy");
            String maHD = kh.getMaKhachHang() + "-" + sdf.format(date);
            for (int i = 0; i < listGioHang.size(); i++) {
                HoaDon hd = listGioHang.get(i);
                hd.setMaHD(maHD);
                hd.setMaKH(kh.getMaKhachHang());
                hd.setMaNV(frmLogin.maNVLogin);
                hd.setNgayBan(sdf2.format(date));
                listGioHang.set(i, hd);
            }
            JTextField txtSoTien = new JTextField(10);
            JPanel myPanel = new JPanel();
            myPanel.add(Box.createHorizontalStrut(10)); // a spacer
            myPanel.add(new JLabel("Số tiền khách đưa:"));
            myPanel.add(txtSoTien);
            int result = JOptionPane.showConfirmDialog(null, myPanel,
                    "Số tiền khách thanh toán", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                double soTienKhachDua = Double.parseDouble(txtSoTien.getText());
                if (soTienKhachDua < tongTien) {
                    JOptionPane.showMessageDialog(this, "Số tiền khách trả chưa đủ !");
                    return;
                } else if (soTienKhachDua > tongTien) {
                    JOptionPane.showMessageDialog(this, "NV trả lại cho khách hàng " + (soTienKhachDua - tongTien) + " VND");
                }
                saveFile();
                JOptionPane.showMessageDialog(this, "Thanh toán thành công !");
                frmSanPham frmSP = new frmSanPham();
                frmSP.loadFile();
                for (int i = 0; i < listGioHang.size(); i++) {
                    updateSoLuong(listGioHang.get(i).getMaSP(), listGioHang.get(i).getSoLuong(), frmSP.listSP);
                }
                frmSP.saveFile();
                sendHDtoEmail(listGioHang, kh.getEmail(), String.valueOf(tongTien));
                listGioHang = new ArrayList<>();
                reset();
            }

        }
    }//GEN-LAST:event_btn_thanhToanActionPerformed
    public void sendHDtoEmail(ArrayList<HoaDon> list, String mail, String sum) {
        try {
            Email email = new SimpleEmail();
            email.setHostName("smtp.googlemail.com");
            email.setSmtpPort(465);
            email.setAuthenticator(new DefaultAuthenticator("hethongsieuthidienmaynpt@gmail.com", "Pt230572"));
            email.setSSLOnConnect(true);
            email.setFrom("hethongsieuthidienmaynpt@gmail.com", "HỆ THỐNG SIÊU THỊ ĐIỆN MÁY");
            email.setSubject("HÓA ĐƠN THANH TOÁN MUA HÀNG");
            String tt = "";
            tt = tt + "                                             ------- THÔNG TIN HÓA ĐƠN MUA HÀNG -------\n\n";
            for (int i = 0; i < list.size(); i++) {
                tt = tt + " Mã sản phẩm: " + list.get(i).getMaSP().toUpperCase() + "\t\t\t\tSố lượng: " + list.get(i).getSoLuong() + "\t\t\t\tĐơn giá: " + list.get(i).getDonGia() + "\n\n";
            }
            email.setMsg(tt + " TỔNG TIỀN SẢN PHẨM (ĐÃ BAO GỒM THUẾ GTGT VÀ CHIẾT KHẤU SẢN PHẨM): " + sum + " VNĐ\n\n"
                    + " Cảm ơn quý khách đã mua hàng tại hệ thống siêu thị của chúng tôi !\n\n"
                    + "               Trân trọng cảm ơn !");
            email.addTo(mail);
            email.send();

        } catch (EmailException e) {
            System.err.println(" ==>> GỬI KHÔNG THÀNH CÔNG !");
        }
    }
    
    public void updateSoLuong(String maSP, int soLuongMua, ArrayList<SanPham> listSP) {
        for (int i = 0; i < listSP.size(); i++) {
            if (maSP.equals(listSP.get(i).getMaSP())) {
                SanPham sp = listSP.get(i);
                sp.setSoLuong(sp.getSoLuong() - soLuongMua);
                listSP.set(i, sp);
            }
        }
    }

    public void reset() {
        getDataKH(loadKH());
        getDataSP(loadSP());
        loadGioHang(listGioHang);
        lbl_maKH.setText("...");
        lbl_tenKH.setText("...");
        lbl_sdtKH.setText("...");
        lbl_diaChiKH.setText("...");
        lbl_emailKH.setText("...");
        tongTien = 0;
        lbl_tongTien.setText("...");
    }

    public void saveFile() {

        try {
            BufferedWriter bw = null; //Khởi tạo
            FileWriter fw = null; //Khởi tạo
            String data = ""; //Tạo một string data bằng rỗng.
            for (int i = 0; i < listGioHang.size(); i++) {
                String row = ""; //tạo hàng rỗng
                row = row + listGioHang.get(i).getMaHD() + "\t";
                row = row + listGioHang.get(i).getMaNV() + "\t";
                row = row + listGioHang.get(i).getMaKH() + "\t";
                row = row + listGioHang.get(i).getMaSP() + "\t";
                row = row + listGioHang.get(i).getSoLuong() + "\t";
                row = row + listGioHang.get(i).getDonGia() + "\t";
                row = row + listGioHang.get(i).getThanhTien() + "\t";
                row = row + listGioHang.get(i).getNgayBan() + "\n";
                data += row;
            }
            fw = new FileWriter("hoadon.txt", true);
            bw = new BufferedWriter(fw);
            bw.write(data);
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(frmBanHang.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void txt_sanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sanPhamActionPerformed

    private void btl_khachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btl_khachHangActionPerformed
        String tuKhoa = txt_searchKH.getText();
        if (tuKhoa.equals("")) {
            getDataKH(loadKH());
        } else {
            ArrayList<KhachHang> listSearch = new ArrayList<>();
            ArrayList<KhachHang> listKH = loadKH();
            for (int i = 0; i < listKH.size(); i++) {
                if (listKH.get(i).getMaKhachHang().contains(tuKhoa) || listKH.get(i).getHoTen().contains(tuKhoa) || listKH.get(i).getEmail().contains(tuKhoa) || listKH.get(i).getSoDienThoai().contains(tuKhoa)) {
                    listSearch.add(listKH.get(i));
                }
            }
            getDataKH(listSearch);
        }
    }//GEN-LAST:event_btl_khachHangActionPerformed

    private void tbl_khach_hangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_khach_hangMouseClicked
        int row = tbl_khach_hang.getSelectedRow();
        String makh = tbl_khach_hang.getValueAt(row, 0).toString();
        ArrayList<KhachHang> listKH = loadKH();
        for (int i = 0; i < listKH.size(); i++) {
            if (makh.equals(listKH.get(i).getMaKhachHang())) {
                kh = listKH.get(i);
                index = i;
                break;
            }
        }
        lbl_maKH.setText(kh.getMaKhachHang());
        lbl_tenKH.setText(kh.getHoTen());
        lbl_sdtKH.setText(kh.getSoDienThoai());
        lbl_diaChiKH.setText(kh.getDiaChi());
        lbl_emailKH.setText(kh.getEmail());

    }//GEN-LAST:event_tbl_khach_hangMouseClicked

    private void tbl_san_phamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_san_phamMouseClicked
        int row = tbl_san_pham.getSelectedRow();
        String makh = tbl_san_pham.getValueAt(row, 0).toString();
        ArrayList<SanPham> listSP = loadSP();
        for (int i = 0; i < listSP.size(); i++) {
            if (makh.equals(listSP.get(i).getMaSP())) {
                sp = listSP.get(i);
                index = i;
                break;
            }
        }
        txt_soLuongSP.setText("1");
    }//GEN-LAST:event_tbl_san_phamMouseClicked
    String maSP;

    private void tbl_gioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_gioHangMouseClicked
        int row = tbl_gioHang.getSelectedRow();
        maSP = tbl_gioHang.getValueAt(row, 0).toString();
    }//GEN-LAST:event_tbl_gioHangMouseClicked

    private void tbl_gioHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_gioHangMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_gioHangMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btl_khachHang;
    private javax.swing.JButton btl_sanPham;
    private javax.swing.JButton btl_thanhToan;
    private javax.swing.JButton btl_themSP;
    private javax.swing.JButton btl_thoat;
    private javax.swing.JButton btl_xoaGioHang;
    private javax.swing.JButton btn_thanhToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_diaChiKH;
    private javax.swing.JLabel lbl_emailKH;
    private javax.swing.JLabel lbl_maKH;
    private javax.swing.JLabel lbl_maNhanVien;
    private javax.swing.JLabel lbl_sdtKH;
    private javax.swing.JLabel lbl_tenKH;
    private javax.swing.JLabel lbl_tongTien;
    private javax.swing.JTable tbl_gioHang;
    private javax.swing.JTable tbl_khach_hang;
    private javax.swing.JTable tbl_san_pham;
    private javax.swing.JTextField txt_sanPham;
    private javax.swing.JTextField txt_searchKH;
    private javax.swing.JTextField txt_soLuongSP;
    // End of variables declaration//GEN-END:variables
}
